Re-factored system-tests builders
The system-tests jobs had their own builder script which made then
unnecessarily different then other standard-CI jobs.

This patch gets rid of the system-tests builder script and makes use of
the standard-ci builder macros instead.

Change-Id: I5ebe785ec090cd09e2dee28c947166f75c2e5b22
Jira-Ticket: https://ovirt-jira.atlassian.net/browse/OVIRT-995
Signed-off-by: Barak Korren <bkorren@redhat.com>

diff --git a/jobs/confs/yaml/builders/system_tests_builders.yaml b/jobs/confs/yaml/builders/system_tests_builders.yaml
--- a/jobs/confs/yaml/builders/system_tests_builders.yaml
+++ b/jobs/confs/yaml/builders/system_tests_builders.yaml
@@ -1,5 +1,16 @@
 - builder:
     name: system-tests
     builders:
-      - shell: !include-raw: shell-scripts/system_tests.sh
-
+      - shell: |
+          ## update extra source if we got it as param ###
+          if ! [ -z ${{CUSTOM_REPOS+x}} ]; then
+            echo "$CUSTOM_REPOS" > ovirt-system-tests/extra_sources
+          fi
+      - shell: |
+          # make sure there's no prefix or lago will fail
+          rm -rf "ovirt-system-tests/deployment-{suite_type}_suite_{version}"
+      - mock_runner:
+          project: 'ovirt-system-tests'
+          distro: '{chroot_distro}'
+          arch: 'x86_64'
+          action: '--execute-script "automation/{suite_type}_suite_{version}.sh"'
